---
        # Default Ansible YAML
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: Master Configurations
  hosts: master
  remote_user: root
  roles:
    - master

- name: Docker Config
  hosts: master
  remote_user: root
  roles:
    - docker

- name: Virt Config
  hosts: virt
  remote_user: root
  roles:
    - virt
