- name: Install Foreman repo
  yum: name=http://yum.theforeman.org/releases/1.10/el7/x86_64/foreman-release.rpm state=present
  tags: packages

- name: Install Foreman installer
  yum: name=foreman-installer state=latest
  tags: packages

