#Install and configure for virtualisation hosts

- name: Install Virt Group
  yum: name=qemu-kvm,libvirt,virt-install state=present

- name: libvirt running
  service: name=libvirtd state=started enabled=yes

- name: libvirt running
  service: name=libvirt-guests state=started enabled=yes

- name: Disable NetworkManager
  service: name=NetworkManager state=stopped enabled=no

- name: Config sysctl for bridge
  sysctl: name="{{ item.cmd }}" value=0 sysctl_set=yes state=present reload=yes
  with_items: virt_sysctl

- name: Config nic for Bridge
  template: src=../templates/enp3s0.js dest=/etc/sysconfig/network-scripts/ifcfg-enp3s0

- name: Add Bridge
  template: src=../templates/br0.enp3s0.js dest=/etc/sysconfig/network-scripts/ifcfg-br0.enp3s0
  notify:
  - restart network


