---
# tasks file for common
#- name: Configure Hostname
#  hostname: name={{ inventory_hostname }}

- name: Install deltarpm
  yum: name=deltarpm state=present
  tags: packages

- name: Install pre-requisites
  yum: name=bash-completion,wget,vim-enhanced,epel-release,lm_sensors state=present
  tags: packages

- include: patch.yml
