---
# tasks file for common
#- name: Configure Hostname
#  hostname: name={{ inventory_hostname }}

- name: Install deltarpm
  yum: name=deltarpm state=present
  tags: packages

- name: Install pre-requisites
  yum: name=bash-completion,wget,vim-enhanced,epel-release,lm_sensors state=present
  tags: packages

- name: Log Rotate syslog file
  template: src=../templates/syslog.j2 dest=/etc/logrotate.d/syslog
- include: patch.yml
