---

# Patch a server

- name: Update server
  yum: name=* state=latest


- name: Check for reboot
  shell: if [ $(rpm -q --last kernel | head -1 |cut -f1 -d " "| sed s/kernel-*//) != $(uname -r) ]; then echo 'reboot'; else echo 'no_reboot'; fi
  register: reboot_hint

- name: Rebooting ...
  shell: sleep 2 && shutdown -r now "Ansible kernel update applied"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_hint == 'reboot'
  register: rebooting

- name: waiting for server to come back
  local_action: 
    module: wait_for 
      host={{ inventory_hostname }}
      port=22
      state=started 
      delay=1 
      timeout=300
  sudo: false
